# Generated by Django 3.1 on 2020-09-03 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200902_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 17, 9, 11, 711145), verbose_name='date published'),
        ),
    ]
